#!/usr/bin/env bash
set -euo pipefail

# Workstation Focus Mode (Deep Block)
# Blocks 100+ distracting and NSFW domains at the OS level.
# Excludes YouTube, Twitch, Reddit, and LinkedIn as requested.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/helpers.sh"

log "═══════════════════════════════════════════════════════"
log "  Focus Mode — Deep Block (100+ Domains)"
log "═══════════════════════════════════════════════════════"

# ── Domain List ──────────────────────────────────────────────────────
DOMAINS=(
  # Major Adult Tube Sites
  "pornhub.com" "www.pornhub.com"
  "xvideos.com" "www.xvideos.com"
  "xnxx.com" "www.xnxx.com"
  "xhamster.com" "www.xhamster.com"
  "redtube.com" "www.redtube.com"
  "youporn.com" "www.youporn.com"
  "youjizz.com" "www.youjizz.com"
  "porn.com" "www.porn.com"
  "nuvid.com" "www.nuvid.com"
  "spankbang.com" "www.spankbang.com"
  "chaturbate.com" "www.chaturbate.com"
  "tube8.com" "www.tube8.com"
  "thumbzilla.com" "www.thumbzilla.com"
  "eporner.com" "www.eporner.com"
  "porntrex.com" "www.porntrex.com"
  "yourporn.sexy" "www.yourporn.sexy"
  "porndig.com" "www.porndig.com"
  "pornmz.com" "www.pornmz.com"
  "beeg.com" "www.beeg.com"
  "fapdu.com" "www.fapdu.com"
  "motherless.com" "www.motherless.com"
  "pornmd.com" "www.pornmd.com"
  "cam4.com" "www.cam4.com"
  "bongacams.com" "www.bongacams.com"
  "stripchat.com" "www.stripchat.com"
  "thisvid.com" "www.thisvid.com"
  "redgifs.com" "www.redgifs.com"
  "aznude.com" "www.aznude.com"
  "pornhat.com" "www.pornhat.com"
  "pornpics.com" "www.pornpics.com"
  "hqporner.com" "www.hqporner.com"
  "sex.com" "www.sex.com"
  "pussyspace.com" "www.pussyspace.com"
  "4tube.com" "www.4tube.com"
  "freeones.com" "www.freeones.com"
  "tnaflix.com" "www.tnaflix.com"
  "empflix.com" "www.empflix.com"
  "heavy-r.com" "www.heavy-r.com"
  "daftsex.com" "www.daftsex.com"
  "javhd.com" "www.javhd.com"
  "pornoz.com" "www.pornoz.com"
  "porndish.com" "www.porndish.com"
  "perfectgirls.net" "www.perfectgirls.net"
  "cumlouder.com" "www.cumlouder.com"

  # Cam & Live Chat
  "jerkmate.com" "www.jerkmate.com"
  "sniffies.com" "www.sniffies.com"
  "xhamsterlive.com" "www.xhamsterlive.com"

  # Adult Creator Platforms
  "onlyfans.com" "www.onlyfans.com"
  "fansly.com" "www.fansly.com"
  "loyalfans.com" "www.loyalfans.com"
  "mym.fans" "www.mym.fans"

  # Hentai, Adult Manga & Image Boards
  "nhentai.net" "www.nhentai.net"
  "tsumino.com" "www.tsumino.com"
  "hentaihaven.xxx" "www.hentaihaven.xxx"
  "hanime.tv" "www.hanime.tv"
  "hentaicube.com" "www.hentaicube.com"
  "doujins.com" "www.doujins.com"
  "hentai2read.com" "www.hentai2read.com"
  "e-hentai.org" "www.e-hentai.org"
  "rule34.xxx" "www.rule34.xxx"
  "gelbooru.com" "www.gelbooru.com"
  "secretclass.us" "www.secretclass.us"
  "mangahe.com" "www.mangahe.com"
  "mangaxo.com" "www.mangaxo.com"
  "nanime.biz" "www.nanime.biz"
  "kissanime.com.ru" "www.kissanime.com.ru"
  "gogoanime.ai" "www.gogoanime.ai"
  "e621.net" "www.e621.net"
  "hdporncomics.com" "www.hdporncomics.com"
  "hentainexus.com" "www.hentainexus.com"
  "nhder.com" "www.nhder.com"
  "hentaiworld.tv" "www.hentaiworld.tv"
  "fetlife.com" "www.fetlife.com"
  "theporndude.com" "www.theporndude.com"
  "literotica.com" "www.literotica.com"
  "listcrawler.eu" "www.listcrawler.eu"

  # Tabloid & Gossip Sites
  "tmz.com" "www.tmz.com"
  "dailymail.co.uk" "www.dailymail.co.uk"
  "thesun.co.uk" "www.thesun.co.uk"
  "buzzfeed.com" "www.buzzfeed.com"
  "perezhilton.com" "www.perezhilton.com"
  "pagesix.com" "www.pagesix.com"
  "hellomagazine.com" "www.hellomagazine.com"
  "usmagazine.com" "www.usmagazine.com"
  "okmagazine.com" "www.okmagazine.com"

  # Gambling & Betting Platforms
  "bet365.com" "www.bet365.com"
  "pokerstars.com" "www.pokerstars.com"
  "888poker.com" "www.888poker.com"
  "draftkings.com" "www.draftkings.com"
  "bovada.lv" "www.bovada.lv"
  "stake.com" "www.stake.com"
  "roobet.com" "www.roobet.com"
  "ignitioncasino.eu" "www.ignitioncasino.eu"

  # Distractions & Social
  "tiktok.com" "www.tiktok.com"
  "9gag.com" "www.9gag.com"
  "4chan.org" "www.4chan.org"

  # Streaming Platforms — Mainstream
  "netflix.com" "www.netflix.com"
  "primevideo.com" "www.primevideo.com"
  "disneyplus.com" "www.disneyplus.com"
  "hulu.com" "www.hulu.com"
  "hbomax.com" "www.hbomax.com"
  "max.com" "www.max.com"
  "paramountplus.com" "www.paramountplus.com"
  "peacocktv.com" "www.peacocktv.com"
  "appletv.com" "www.appletv.com" "tv.apple.com"
  "tubitv.com" "www.tubitv.com"
  "pluto.tv" "www.pluto.tv"
  "mubi.com" "www.mubi.com"
  "starz.com" "www.starz.com"
  "showtime.com" "www.showtime.com"

  # Streaming Platforms — Anime
  "crunchyroll.com" "www.crunchyroll.com" "beta.crunchyroll.com" "static.crunchyroll.com"
  "hidive.com" "www.hidive.com"
  "vrv.co" "www.vrv.co"
  "funimation.com" "www.funimation.com"

  # Manga / Comic Reading
  "mangafire.to" "www.mangafire.to"
  "marvel.com" "www.marvel.com"
  "comix.to" "www.comix.to"
  "mangadex.org" "www.mangadex.org" "mangadex.cc" "mangadex.tv"
  "mangakakalot.com" "www.mangakakalot.com" "mangakakalot.tv"
  "manganelo.com" "www.manganelo.com"
  "mangareader.to" "www.mangareader.to"
  "mangapark.net" "www.mangapark.net" "mangapark.com" "mangapark.io"
  "fanfox.net" "www.fanfox.net" "m.fanfox.net"
  "mangapanda.com" "www.mangapanda.com"
  "mangakomi.com" "www.mangakomi.com"
  "mangahere.cc" "www.mangahere.cc" "mangahere.onl"
  "manga4life.com" "www.manga4life.com"
  "toongod.org" "www.toongod.org"
  "comicasura.net" "www.comicasura.net" "asuracomic.net" "www.asuracomic.net"
  "manhwatop.com" "www.manhwatop.com"
  "topmanhua.com" "www.topmanhua.com"
  "mangafreak.net" "www.mangafreak.net"
  "mangahasu.com" "www.mangahasu.com"
  "tapas.io" "tapas.io"
  "tappytoon.com" "www.tappytoon.com"
  "toomics.com" "www.toomics.com"
  "lezhin.com" "www.lezhin.com"
  "manhuaplus.com" "www.manhuaplus.com"
  "mangairo.com" "www.mangairo.com"
  "mangatown.com" "www.mangatown.com"
  "mangainn.net" "www.mangainn.net"
  "mangacanblog.com" "www.mangacanblog.com"
  "komikcast.com" "www.komikcast.com"
  "westmanga.info" "www.westmanga.info"
  "mangasuki.online" "www.mangasuki.online"
  "bacamanga.id" "www.bacamanga.id"
  "shimadascans.com" "www.shimadascans.com"
  "flamecomics.com" "www.flamecomics.com"
  "luminousscans.com" "www.luminousscans.com"
  "realmscans.com" "www.realmscans.com"
  "drakescans.com" "www.drakescans.com"
  "nightscans.net" "www.nightscans.net"

  # Browser Game Portals
  "crazygames.com" "www.crazygames.com"
  "poki.com" "www.poki.com"
  "addictinggames.com" "www.addictinggames.com"
  "kongregate.com" "www.kongregate.com"
  "armorgames.com" "www.armorgames.com"
  "y8.com" "www.y8.com"
  "friv.com" "www.friv.com" "frivclassic.com"
  "miniclip.com" "www.miniclip.com"
  "agame.com" "www.agame.com"
  "kizi.com" "www.kizi.com"
  "lagged.com" "www.lagged.com"
  "newgrounds.com" "www.newgrounds.com"
  "coolmathgames.com" "www.coolmathgames.com"
  "abcya.com" "www.abcya.com"
  "gamerpix.com" "www.gamerpix.com"
  "pogo.com" "www.pogo.com"
  "shockwave.com" "www.shockwave.com"
  "freeonlinegames.com" "www.freeonlinegames.com" "fog.com"
  "nitrome.com" "www.nitrome.com"
  "silvergames.com" "www.silvergames.com"
  "1001games.com" "www.1001games.com"
  "gameforge.com" "www.gameforge.com"
  "a10.com" "www.a10.com"
  "keygames.com" "www.keygames.com"
  "mathplayground.com" "www.mathplayground.com"
  "retrogames.online" "www.retrogames.online" "playretrogames.online"
  "emuos.net" "www.emuos.net"
  "itch.io" "gamejolt.com"

  # IO Games & Browser Time-Wasters
  "agar.io" "www.agar.io"
  "slither.io" "www.slither.io"
  "krunker.io" "www.krunker.io"
  "skribbl.io" "www.skribbl.io"
  "diep.io" "www.diep.io"
  "surviv.io" "www.surviv.io"
  "venge.io" "www.venge.io"
  "kour.io" "www.kour.io"
  "lolbeans.io" "www.lolbeans.io"
  "hordes.io" "www.hordes.io"
  "poxel.io" "www.poxel.io"
  "drift.io" "www.drift.io"
  "slay.one" "www.slay.one"
  "shellshockers.io" "www.shellshockers.io"
  "paper.io" "www.paper.io"
  "wormate.io" "www.wormate.io" "worms.zone" "www.worms.zone"
  "play2048.co" "2048game.com" "play2048.co"
  "littlealchemy2.com" "littlealchemy.com"
  "orteil.dashnet.org"
  "wikigame.com" "www.thewikigame.com"
  "jigsawplanet.com" "www.jigsawplanet.com"
  "arkadium.com" "www.arkadium.com"
  "wordlegame.org" "www.wordlegame.org"
  "geoguessr.com" "www.geoguessr.com"
  "slope.game" "slopeunblocked.game"
  "tunnelrush.com" "tunnelrush3d.com"
  "retrobowl.me" "www.retrobowl.me"
  "bloxd.io" "www.bloxd.io"
  "evowars.io" "www.evowars.io"
  "voxiom.io" "www.voxiom.io"
  "starblast.io" "www.starblast.io"
  "mope.io" "www.mope.io"
  "flyordie.io" "www.flyordie.io"
  "hole-io.com" "www.hole-io.com"
  "smashkarts.io" "www.smashkarts.io"
  "stabfish.io" "www.stabfish.io"
  "duckpark.io" "www.duckpark.io"
  "battledudes.io" "www.battledudes.io"
  "tileman.io" "www.tileman.io"
  "brutalmania.io" "www.brutalmania.io"
  "frontwars.io" "www.frontwars.io"
  "warcall.io" "www.warcall.io"
  "chompers.io" "www.chompers.io"
  "mk48.io" "www.mk48.io"
  "overtide.io" "www.overtide.io"
  "gulper.io" "www.gulper.io"
  "rocketgoal.io" "www.rocketgoal.io"
  "meeland.io" "www.meeland.io"
  "cuberealm.io" "www.cuberealm.io"
  "minigiants.io" "www.minigiants.io"
  "veck.io" "www.veck.io"
  "miniblox.io" "www.miniblox.io"
  "pixelwarfare.io" "www.pixelwarfare.io"
  "rocketbotroyale.com" "www.rocketbotroyale.com"

  # Streaming Platforms — Brazilian / LatAm
  "globoplay.com" "www.globoplay.com" "globoplay.globo.com"
  "starplus.com" "www.starplus.com" "star-plus.com"
  "clarovideo.com" "www.clarovideo.com"
  "vix.com" "www.vix.com"

  # Streaming Platforms — Sports
  "dazn.com" "www.dazn.com"
  "espn.com" "www.espn.com" "plus.espn.com"
)

# ── Update /etc/hosts ───────────────────────────────────────────────
HOSTS_FILE="/etc/hosts"

# Unlock if already immutable
if lsattr "$HOSTS_FILE" 2>/dev/null | grep -q "^....i"; then
  log "Unlocking $HOSTS_FILE for updates..."
  sudo chattr -i "$HOSTS_FILE"
fi

log "Adding distraction blocks to $HOSTS_FILE (Deep Block)..."

# Backup current hosts if not already backed up
if [[ ! -f "${HOSTS_FILE}.bak" ]]; then
  sudo cp "$HOSTS_FILE" "${HOSTS_FILE}.bak"
fi

# Filter and append only missing domains
for domain in "${DOMAINS[@]}"; do
  if ! grep -qF "$domain" "$HOSTS_FILE"; then
    echo "127.0.0.1 $domain" | sudo tee -a "$HOSTS_FILE" > /dev/null
  fi
done

# ── Lock /etc/hosts ─────────────────────────────────────────────────
log "Locking $HOSTS_FILE (making it immutable)..."
sudo chattr +i "$HOSTS_FILE"

log "Focus Mode setup complete."
